version: "3.9"

services:
  project1-neo4j:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: project1-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    environment:
      - NEO4J_AUTH=neo4j/project1phase1
    # command: >
    #   bash -c "
    #   if [ ! -d /var/lib/neo4j/data/databases/system ]; then
    #     neo4j-admin dbms set-initial-password project1phase1;
    #   fi &&
    #   neo4j start &&
    #   echo 'Waiting for Neo4j to start...' &&
    #   sleep 20 &&
    #   python3 /app/scripts/data_loader.py &&
    #   tail -f /dev/null"
